name: CI Link Checker
on: 
  workflow_dispatch
jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps: 
    - uses: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    -name: Install broken-link-checker
      run: npm install -g broken-link-checker

    - name: Run Link Checker 
      run: npm broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro
